version: '3.8'
services:
  solr:
    image: solr:9-slim
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
    command:
      - solr-precreate
      - books
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8983/solr/books/admin/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  schema-init:
    image: curlimages/curl:latest
    depends_on:
      solr:
        condition: service_healthy
    volumes:
      - ./init-book-schema.sh:/init-book-schema.sh
    command: ["/bin/sh", "/init-book-schema.sh"]
    labels:
      io.quarkus.devservices.compose.ignore: true

volumes:
  solr_data:
