version: '3.8'
services:
  solr:
    image: solr:9-slim
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
    command:
      - solr-precreate
      - books

volumes:
  solr_data: